name: Build and Push

on:
  push:
    paths:
      - 'jenkins/**'
      - 'dind-agent/**'
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
    paths:
      - 'jenkins/**'
      - 'dind-agent/**'

env:
  REPO: ${{ vars.REPO }}

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      REPO: ${{ env.REPO }}
    steps:
      -
        name: Prepare Outputs
        run: |
          echo "REPO=${{ env.REPO }}" >> $GITHUB_OUTPUT


  build-and-push:
    needs: [prepare-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: ./jenkins
            image: ${{ needs.prepare-matrix.outputs.REPO }}/jenkins-server
          - path: ./dind-agent
            image: ${{ needs.prepare-matrix.outputs.REPO }}/jenkins-agent
    steps:
      -
        name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db #3.6.1
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
        with:
          images: ${{ matrix.image }}
          tags: |
            type=ref,event=tag
            type=raw,value=head
      -
        name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build Image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 #v6.7.0
        with:
          context: ${{ matrix.path }}
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          file: ${{ matrix.path }}/Dockerfile
          tags: |
            ${{ steps.meta.outputs.tags }}
