# TODO: Update to pinned versions
# TODO: check tags
name: build-and-push

on:
  push:
    paths:
      - 'jenkins/**'
      - 'dind-agent/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_SERVER: ${{ github.repository_owner }}/jenkins-server
      IMAGE_AGENT: ${{ github.repository_owner }}/jenkins-agent
    steps:
      - name: Print repository owner
        run: echo "Repository owner is ${{ github.repository_owner }}"
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,value=latest
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push the server
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./jenkins/Dockerfile
          image: ${{ env.IMAGE_SERVER }}
          tags: ${{ steps.meta.outputs.tags }}
      -
        name: Build and push the agent
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./dind-agent/Dockerfile
          image: ${{ env.IMAGE_AGENT }}
          tags: ${{ steps.meta.outputs.tags }}
